# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/eth_ddr3_hdmi/eth_ddr3_hdmi.srcs/sources_1/ip/bram_hdmi_data/bram_hdmi_data.xci
# IP: The module: 'bram_hdmi_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/eth_ddr3_hdmi/eth_ddr3_hdmi.srcs/sources_1/ip/bram_hdmi_data/bram_hdmi_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_hdmi_data'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/eth_ddr3_hdmi/eth_ddr3_hdmi.srcs/sources_1/ip/bram_hdmi_data/bram_hdmi_data.xci
# IP: The module: 'bram_hdmi_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/eth_ddr3_hdmi/eth_ddr3_hdmi.srcs/sources_1/ip/bram_hdmi_data/bram_hdmi_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_hdmi_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
