# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/bram_ddr3_hdmi_test_pin.xdc

# IP: ip/wr_fifo/wr_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wr_fifo || ORIG_REF_NAME==wr_fifo} -quiet] -quiet
