@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Fri Jan 20 22:15:33 +0800 2023
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 1dca9d569dda4497a79353c1acfc73a6 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L fifo_generator_v13_2_4 -L blk_mem_gen_v8_4_3 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_bram_ddr3_hdmi_test_behav xil_defaultlib.tb_bram_ddr3_hdmi_test xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto 1dca9d569dda4497a79353c1acfc73a6 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L fifo_generator_v13_2_4 -L blk_mem_gen_v8_4_3 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_bram_ddr3_hdmi_test_behav xil_defaultlib.tb_bram_ddr3_hdmi_test xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
