# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/eth_ddr3_hdmi/eth_ddr3_hdmi.srcs/sources_1/ip/rd_fifo/rd_fifo.xci
# IP: The module: 'rd_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/eth_ddr3_hdmi/eth_ddr3_hdmi.srcs/sources_1/ip/rd_fifo/rd_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'rd_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/eth_ddr3_hdmi/eth_ddr3_hdmi.srcs/sources_1/ip/rd_fifo/rd_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'rd_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/eth_ddr3_hdmi/eth_ddr3_hdmi.srcs/sources_1/ip/rd_fifo/rd_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rd_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/eth_ddr3_hdmi/eth_ddr3_hdmi.srcs/sources_1/ip/rd_fifo/rd_fifo.xci
# IP: The module: 'rd_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/eth_ddr3_hdmi/eth_ddr3_hdmi.srcs/sources_1/ip/rd_fifo/rd_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'rd_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/eth_ddr3_hdmi/eth_ddr3_hdmi.srcs/sources_1/ip/rd_fifo/rd_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'rd_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/eth_ddr3_hdmi/eth_ddr3_hdmi.srcs/sources_1/ip/rd_fifo/rd_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rd_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
