set_property PACKAGE_PIN M6 [get_ports {HDMI_OEN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HDMI_OEN[0]}]
set_property PACKAGE_PIN G1 [get_ports {TMDS_data_p[0]}]
set_property PACKAGE_PIN H2 [get_ports {TMDS_data_p[1]}]
set_property PACKAGE_PIN K1 [get_ports {TMDS_data_p[2]}]
set_property PACKAGE_PIN Y18 [get_ports clk]
set_property PACKAGE_PIN F20 [get_ports rst_n]
set_property PACKAGE_PIN E1 [get_ports TMDS_clk_p]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets rd_clk]
